### ISSUE TITLE
Traefik 3 migration problems

### ISSUE THREAD

**Issue by maximuskowalski** [saltyorg/Sandbox#215] opened 2022-12-28 08:18 UTC
Going to try to keep moving rather than get bogged down on issues so these are the apps not working currently.

- [x] bookstack - DB role
- [x]  booksonic
- [x]  calibre
- [x]  calibre-web
- [ ]  delugevpn, needs proper test too.
- [x]  gitea - another DB role
- [x] guacamole - https://github.com/saltyorg/Sandbox/commit/9720877abade639b83b8afe72c5fa91a7997e6c8
- [x] invoiceninja - DB
- [x] homeassistant - gateway timeout, no docs, might just be a URL thing
- [x] joplin - Bad Gateway - DB related
- [x] koel - DB
- [ ] minecraft related roles - I don't know how to test other than the install. Roles are :- `sandbox-mcrouter, sandbox-minecraft, sandbox-minecraft-bedrock`
- [x] miniflux - 404 [  `[FATAL] Unable to connect to the database: dial tcp: lookup miniflux-postgres: Try again` ]
- [ ] moviematch - probably just needs real plex instance [ `error: Uncaught (in promise) TypeError: Cannot read property 'map' of undefined
  const availableLibraryNames = sections.MediaContainer.Directory.map(` ]
- [x] mqtt - installs fine but not tested
- [x] nabarr - installs fine, untested
- [ ]  nextcloud - installs fine - may need to convert labels, regex middleware
- [x] node-red - 404 probably needs dehyphening - fixed https://github.com/saltyorg/Sandbox/commit/0cf3105dac97b2178e1addf76ca4e2ca580ecfd1
- [x] omegabrr - 404 - may just need config, no idea what it does.
- [x] paperless-ngx - has hyphen [ Error: Error -3 connecting to paperless_redis:6379. Temporary failure in name resolution..]
- [x] photoprism - might need testing on real server - [see my error here](https://github.com/saltyorg/Sandbox/issues/215#issuecomment-1371605924)
- [ ]  qbittorrentvpn - needs proper testing with a VPN account
- [ ] rdtclient - needs proper testing with a real debrid account
- [ ]  rocketchat - no wiki so unsure if other steps reqd - timeout connecting to mongodb ( I think )
- [ ] sabthrottle - installs but not able to test properly
- [x] stash - installs OK but have an error after running initial first run wizard - `TypeError: Failed to fetch dynamically imported module: https://stash._mydomain_._com_/assets/Settings.b9790d5d.js` See https://github.com/saltyorg/Sandbox/issues/215#issuecomment-1384467617 - https://github.com/saltyorg/Sandbox/commit/d3e6da7bbb4c980134e403df7e1749803aa205d9
- [ ] syncthing - installs fine, syncing things untested.
- [x]  not sure how to deal with `olivetin_traefik_middleware_api: "{{ traefik_global_middleware }}"`
- [x] traefik_robotstxt  - labels, regex middleware
- [ ] transmissionvpn - needs testing with a VPN account
- [x] # default to blank
       `whisparr_api_key: ` # should this get an ""
- [ ] Ombi-X - should be migrated to an instance app instead of an arrX app
- [ ] requestrrX - should be migrated to an instance app instead of an arrX app
- [ ]  rfloodX - should be migrated to an instance app instead of an arrX app
- [x] tandoor - fixed https://github.com/saltyorg/Sandbox/commit/3514327eae666c12b62ae61b495a67492919eafc
- [x] tdarr
- [x] teamspeak (no web ui)
- [x] telegraf (no web ui)
- [x] thelounge
- [x] tika (no web ui)
- [x] tqm (no web ui)
- [x] trackarr
- [x] trilium
- [x] tubearchivist
- [x] tvheadend
- [x] unifi
- [x] unmanic
- [x] unpackerr (no web ui)
- [x] uptime-kuma
- [x] varken (no web ui)
- [x] vaultwarden
- [x] vnstat
- [x] whisparr
- [x] wikijs
- [x] wireguard
- [x] wizarr
- [x] wordpress
- [x] wrapperr
- [x] xbackbone - fixed https://github.com/saltyorg/Sandbox/commit/a044f2aaae05331dc91da98f73d1c49006365460
- [x] xteve - I believe there is no ui, but app output is there (I presume the guide XML) so it seems fine
- [x] yacht
- [x] znc

**Comment by saltydk** [comment] 2022-12-28 16:41
https://github.com/popeen/Booksonic-Air/issues/23 may be the cause, you could try and approach LSIO about it?

**Comment by saltydk** [comment] 2022-12-28 18:50
```yaml
booksonic_docker_envs_default:
  PUID: "{{ uid }}"
  PGID: "{{ gid }}"
  TZ: "{{ tz }}"
  JAVA_OPTS: "-Dserver.use-forward-headers=true"``` seems to resolve the issue you wrote on discord but to me it seems like it has other issues as well.

**Comment by maximuskowalski** [comment] 2022-12-28 23:37
`JAVA_OPTS: "-Dserver.use-forward-headers=true"`
  
  That was what fixed airsonic, I did try running with that but I don't think dockerfile is set up to take the ENV. Will be aiming to get as much as possible working ASAP for now.

**Comment by saltydk** [comment] 2022-12-28 23:38
It fixes the http vs https issue, since they use the same framework if I had to take a guess.

**Comment by saltydk** [comment] 2022-12-28 23:39
https://github.com/linuxserver/docker-booksonic-air/blob/4d5d9530a4b2b92fd452a4d1c98b7cc31256662f/root/etc/services.d/booksonic-air/run#L25

**Comment by maximuskowalski** [comment] 2022-12-28 23:43
Wait.. I have been looking in the wrong spot then. :|
https://gitlab.com/Linuxserver.io/docker-booksonic-air/-/blob/master/Dockerfile

**Comment by saltydk** [comment] 2022-12-28 23:44
Dockerfile doesn't have anything to do with runtime stuff though. That is the entrypoint and S6 services in this case.

**Comment by maximuskowalski** [comment] 2022-12-28 23:47
That is what I meant by "looking in the wrong spot" not the github vs gitlab.

**Comment by maximuskowalski** [comment] 2023-01-03 11:30
Have merged my last lot of changes, TESTED UP TO L's, the  Ms - Ss still to check. 
Added to first post things that need to be followed up.

**Comment by owine** [comment] 2023-01-03 22:29
`not sure how to deal with olivetin_traefik_middleware_api: "{{ traefik_global_middleware }}"`

  I have no idea why this is there and it can simply be nuked.

**Comment by owine** [comment] 2023-01-03 23:04
Committed changes that should get the db roles working again. Needed to replace var used for mysql root password since it changed with the new image.

https://github.com/saltyorg/Sandbox/commit/2263c1a41ec64d8d3dd9fa6ec9b081c63dd48505

**Comment by owine** [comment] 2023-01-03 23:22
> Committed changes that should get the db roles working again. Needed to replace var used for mysql root password since it changed with the new image.
> 
> [2263c1a](https://github.com/saltyorg/Sandbox/commit/2263c1a41ec64d8d3dd9fa6ec9b081c63dd48505)

This will cause CI go fail as the var changes correspond to changes on the Saltbox traefik3 branch.

**Comment by RaneyDazed** [comment] 2023-01-04 00:10
makemkv seems to work fine, medusa is giving me an update error, not sure if its expected? 
```yaml
2023-01-03 17:03:40 WARNING  Thread_0 :: [] Unable to contact github, can't check for update: 
ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with URL:
 /orgs/pymedusa (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at
 0x7f8b1cf50c40>: Failed to establish a new connection: [Errno -3] Try again'))"))
```

**Comment by maximuskowalski** [comment] 2023-01-04 00:22
No problems with medusa for me and I was able to check for update.

**Comment by saltydk** [comment] 2023-01-04 05:45
miniflux is broken because these are empty:
```yaml
miniflux_postgres_username:
miniflux_postgres_password:
```

**Comment by saltydk** [comment] 2023-01-04 05:47
I suspect the multi-instance work made the omit break the intended behavior.

**Comment by saltydk** [comment] 2023-01-04 07:46
https://github.com/saltyorg/Sandbox/commit/0fb8aba4f1fc3913676a55e0ad38a5b6456cf9df should fix miniflux.

**Comment by saltydk** [comment] 2023-01-04 07:50
I'm not getting gateway timeout on homeassistant. May want to recheck that.

**Comment by saltydk** [comment] 2023-01-04 07:50
> > Committed changes that should get the db roles working again. Needed to replace var used for mysql root password since it changed with the new image.
> > [2263c1a](https://github.com/saltyorg/Sandbox/commit/2263c1a41ec64d8d3dd9fa6ec9b081c63dd48505)
> 
> This will cause CI to fail from this point forward as the var changes correspond to changes on the Saltbox traefik3 branch.

Should be fine after I made a temporary edit to checkout the traefik3 saltbox branch in the CI.

**Comment by maximuskowalski** [comment] 2023-01-04 22:37
> I'm not getting gateway timeout on homeassistant. May want to recheck that.

So yours worked fine and I can tick it off? I have a crappy VPS it sometimes doesn't work so good.

**Comment by maximuskowalski** [comment] 2023-01-05 00:57
Photoprism: fails on my vps - no /dev/dri/
```yml
2023-01-05 11:52:51,247 p=1549934 u=root n=ansible | TASK [photoprism : Resources | Tasks | Docker | Create Docker Container | Create Docker Container] **********************************************************
2023-01-05 11:52:51,247 p=1549934 u=root n=ansible | Thursday 05 January 2023  11:52:51 +1100 (0:00:00.124)       0:01:40.372 ****** 
2023-01-05 11:52:58,637 p=1549934 u=root n=ansible | fatal: [localhost]: FAILED! => {"attempts": 1, "changed": false, "msg": "Error starting container 58e6fd4b95f3fd82a78238e7a8f6eaa211beaf70bc3cce1aab34b7c3b570e374: 500 Server Error for http+docker://localhost/v1.41/containers/58e6fd4b95f3fd82a78238e7a8f6eaa211beaf70bc3cce1aab34b7c3b570e374/start: Internal Server Error (\"error gathering device information while adding custom device \"/dev/dri\": no such file or directory\")"}
```

**Comment by RaneyDazed** [comment] 2023-01-06 00:46
I think I made that pr, should I remove that? or I guess should it be removed? Not sure how we're doing this.

**Comment by maximuskowalski** [comment] 2023-01-06 00:54
What PR?

**Comment by RaneyDazed** [comment] 2023-01-06 00:55
for photoprism. I think I added /dev/dri when testing in SB mod. Must have forgotten to remove?

**Comment by maximuskowalski** [comment] 2023-01-06 00:58
Oh, I am not sure - plex and other apps use it if it exists, so perhaps it might need to be checked for existence first. Once I get through all the role tests I'll come back to trying to fix things unless they have already been fixed.

If you want to try to fix it you are more than welcome to, just remember to do it on the T3 branch and test it on the T3 branch.

**Comment by owine** [comment] 2023-01-06 01:02
Remove it as a default (set to blank) and do this in the role

```
- name: Docker Devices Task
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/set_docker_devices_variable.yml"
  when: gpu.intel or gpu.nvidia
  ```

**Comment by RaneyDazed** [comment] 2023-01-06 01:08
Ok, give me a sec to get vscode up : )

**Comment by owine** [comment] 2023-01-06 02:46
Looks like

- [ ] notifiarr
- [ ] unpackerr

Need vars looked at

**Comment by owine** [comment] 2023-01-16 18:15
`whisparr_api_key:`

This is how the arrs are in the main repo so I think this is fine

**Comment by owine** [comment] 2023-01-16 19:25
Stash works, issue is related to https://github.com/stashapp/stash/wiki/Authentication-Required-When-Accessing-Stash-From-the-Internet - since we deploy Authelia by default we should set the config bit appropriately

**Comment by owine** [comment] 2023-01-16 20:17
Testing the following roles:

- [ ] tandoor
- [ ] tdarr
- [ ] teamspeak
- [ ] telegraf
- [ ] thelounge
- [ ] tika
- [ ] tqm
- [ ] trackarr
- [ ] trilium
- [ ] tubearchivist
- [ ] tvheadend
- [ ] unifi
- [ ] unmanic
- [ ] unpackerr
- [ ] uptime-kuma
- [ ] varken
- [ ] vaultwarden
- [ ] vnstat
- [ ] whisparr
- [ ] wikijs
- [ ] wireguard
- [ ] wizarr
- [ ] wordpress
- [ ] wrapperr
- [ ] xbackbone
- [ ] xteve
- [ ] yacht
- [ ] znc

**Comment by keldian** [comment] 2023-02-12 14:02
>     omegabrr - 404 - may just need config, no idea what it does.

At the moment the root URL doesn't point to anything. There's no frontend—it's strictly for API calls via `https://omegabrr.domain.tld/api/webhook/trigger`. I suppose we can have Traefik rewrite the root URL to that but meh.

**Comment by saltydk** [comment] 2023-02-21 13:55
What is the current status, anything that needs my intervention or?

**Comment by maximuskowalski** [comment] 2023-02-28 23:26
Trying to keep first post updated - unchecked boxes need some looking at but I believe we have made a full first pass over everything. Some regex things that I am not sure about from that post.

nextcloud - installs fine - may need to convert labels, regex middleware
traefik_robotstxt - labels, regex middleware

**Comment by saltydk** [comment] 2023-02-28 23:38
Maybe edit the main post to have the full status as we go along as this all seems very confusing.

**Comment by saltydk** [comment] 2023-02-28 23:43
I don't see any problems with the Nextcloud regex middleware as I don't think that went through any changes.

**Comment by saltydk** [comment] 2023-02-28 23:51
traefik_robotstxt: Should be fixed now.

**Closed** 2023-09-17 17:23 UTC
Labels: bug, help wanted
